/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ALGO_3;

import ALGO_3.main.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
